title: TheRouter - APP Modular Solution
email: kymjs123@gmail.com
description: TheRouter A cross-platform dynamic routing framework for Android and iOS. 
baseurl: "" 
url: ""
permalink: /docs/:year/:month/:day/:title 

company_name: LaLaMove

markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables 
    
plugins:
  - jekyll-feed
